builds:
  - id: amd64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

  - id: arm64
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goarm:
      - "7"

archives:
  - formats: [zip]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"