name: goreleaser

on:
    push:
      tags:
        - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Run GoReleaser with Cross-Compilation Support
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Use goreleaser-cross Docker image for CGO cross-compilation
          DOCKER_IMAGE: ghcr.io/goreleaser/goreleaser-cross:v1.21.5