name: goreleaser

on:
    push:
      tags:
        - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Install SQLite dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libsqlite3-dev gcc build-essential libc6-dev gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
      -
        name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.21'
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CGO_ENABLED: 1
          CC: arm-linux-gnueabihf-gcc
          CXX: arm-linux-gnueabihf-g++
          GOOS: linux
          GOARCH: arm
          GOARM: 7